### ISSUE TITLE
Snooze text in reminder drop downs is not visible

### ISSUE THREAD

**Issue by sethdeckard** [leoandreotti/slack-dark-theme#1]
It's actually barely visible but only if you highlight the selection. I'll put together a PR when I get a chance.

**Comment by leoandreotti** [comment]
Hi @sethdeckard,

would you mind in attach a screenshot of that? I have placed a lot of fixes now for texts fields and I want to make sure that I fix exactly the one that you are talking about.

Thank you for your contribution

**Comment by sethdeckard** [comment]
![image](https://user-images.githubusercontent.com/59431/48631518-b79ccd00-e98c-11e8-8ac3-1e560dcd29dc.png)

Here's a screenshot, sorry I've been too busy these past two weeks to take another look at it.

**Comment by leoandreotti** [comment]
Hi @sethdeckard, I have published a fix for this. Please clear cache and restart your app.

![image](https://user-images.githubusercontent.com/34519982/48637381-b54e6900-e9b4-11e8-9b24-befffc16f0d7.png)


Thank you for your contribution and I am sorry for the delay.

**Comment by sethdeckard** [comment]
Nice, thank you!
