### ISSUE TITLE
nice theme, but how to keep user's name colors

### ISSUE THREAD

**Issue by jprobichaud** [leoandreotti/slack-dark-theme#10]
Your theme is really good and addresses so much little details already.  Thanks!  

The only detail I couldn't see how to change is people's names (that you can click on and get the user profile) are washed out of color using your theme.  I was using that visual cue a lot and I'd like to get the colors back for them.  Could you point me to which property I need to change to get them back?

Thanks!

**Comment by leoandreotti** [comment]
Hi Jp, thank you for your contribution. I am a little low in time at this moment but I can see that there are, still, several style fixes and I am counting with your contribution on pointing that. Thank you!!

Could you please attach a screen of where you would like to have the text style fixed?

Regards.

**Comment by leoandreotti** [comment]
Hi @jprobichaud,

I have updated CSS and instructions for Slack 4.0 on Mac and Linux. Please try again using the new instructions.

**Comment by jprobichaud** [comment]
thanks for following up on this!  As soon as I can get my hands on slack 4.0 for linux, I'll try that (so far, I only see 3.4 available)

**Comment by leoandreotti** [comment]
Hi @jprobichaud,

I've tested and the theme will work properly for 3.4.
