### ISSUE TITLE
Slack 3.4.2 Breaks Theme

### ISSUE THREAD

**Issue by chrisowens517** [leoandreotti/slack-dark-theme#11]
Slack updated to version 3.4.2 on Windows 10 this morning and the theme broke completely. There are no signs of the theme working.

**Comment by leoandreotti** [comment]
Hi Chris,

Have you reconfigured your interop.js? everytime slack updates, you must reconfigure it.

I haven't had much time to work in the project, but I am scheduled for the next 15 days to work on it. if reconfigure don't work I will fix this.

**Comment by chrisowens517** [comment]
Hi Leo,
I have reconfigured the ssb-interop.js file with no success. I've also
tried a number of other, similar, options for setting a dark mode for
slack, but none of them have had any success. I believe they may have
reconfigured how the styles are being loaded.

Thanks,
Chris

**Comment by leoandreotti** [comment]
Hi Chris,

thanks for your feedback. I will update mine slack now and start to work in a fix. Thank you!

**Comment by leoandreotti** [comment]
Hi Chris,

I am using now 3.4.2 on Mac, just updated, and I am able to activate the theme using the code

`// First make sure the wrapper app is loaded
document.addEventListener("DOMContentLoaded", function() {

  // Then get its webviews
  let webviews = document.querySelectorAll(".TeamView webview");

  // Fetch our CSS in parallel ahead of time
  const cssPath = 'https://leoandreotti.github.io/slack-dark-theme/slackdarktheme.css';
  let cssPromise = fetch(cssPath).then(response => response.text());

  let customCustomCSS = `
  :root {
    /* Modify these to change your theme colors: */
    --primary: #61AFEF;
    --text: #CCC;
    --background: #222;
    --background-elevated: #222;
  }
  `

  // Insert a style tag into the wrapper view
  cssPromise.then(css => {
    let s = document.createElement('style');
    s.type = 'text/css';
    s.innerHTML = css + customCustomCSS;
    document.head.appendChild(s);
  });

  // Wait for each webview to load
  webviews.forEach(webview => {
    webview.addEventListener('ipc-message', message => {
        if (message.channel == 'didFinishLoading')
          // Finally add the CSS into the webview
          cssPromise.then(css => {
              let script = `
                    let s = document.createElement('style');
                    s.type = 'text/css';
                    s.id = 'slack-custom-css';
                    s.innerHTML = \`${css + customCustomCSS}\`;
                    document.head.appendChild(s);
                    `
              webview.executeJavaScript(script);
          })
    });
  });
});`

did you try using help -> clear cache and restart?

**Comment by leoandreotti** [comment]
Is the same code as in the instructions.

**Comment by chrisowens517** [comment]
Hi Leo,
I've cleared cache and restarted, added and re-added the code, and still am
not getting the theme. I'm running Windows 10 Pro for Workstations
10.0.18362 Build 18362. I've decided to move up to the latest beta build of
Slack which doesn't even have the interop.js file in the payload anymore.
Looks like I'll have to wait until Slack adds dark mode as a feature.

Thanks!

**Comment by leoandreotti** [comment]
Hi @chrisowens517 

I have updated CSS and instructions for Slack 4.0 for Mac and Linux. As you are using Windows, I've made some research and didn't find anything for Windows yet.

Once I find anything for Windows I will update the instructions.

**Comment by leoandreotti** [comment]
Hi @chrisowens517,

just posted a way to have it working on windows. Still working to have the style full compatible.
