### ISSUE TITLE
Method no longer works in Slack desktop client 4.0.0

### ISSUE THREAD

**Issue by tmursch** [leoandreotti/slack-dark-theme#14]
The Slack desktop client 4.0.0 introduced numerous changes to the backend and the methods to implement this custom dark theme no longer work.

**Comment by leoandreotti** [comment]
Hi @BadPackets, have you tried with the new version of the instructions as I sent this morning?

I am using on Mac with that method.

**Comment by tmursch** [comment]
> For Windows I still don't have found an option since there is no more ssb-interop.bundle.js file. Once I find a solution I will update here.

**Comment by leoandreotti** [comment]
OK. for windows, Once I find any method I will keep everyone posted.

**Comment by leoandreotti** [comment]
Hi @BadPackets,

just posted a way to have it working on windows. Still working to have the style full compatible.

**Comment by tmursch** [comment]
Thanks, it works mostly. As you noted, the header has issues. I also see the main text input box has some style issues (pictured below).
![image](https://user-images.githubusercontent.com/32589462/61330316-2d835d80-a7d4-11e9-8042-1a78d84e5b06.png)
![image](https://user-images.githubusercontent.com/32589462/61330326-34aa6b80-a7d4-11e9-8679-ea7768d28140.png)

**Comment by leoandreotti** [comment]
@BadPackets I've tested to reset slack using Help -> Troubleshooting -> Reset App Data and that completely worked for me on windows.

Would you mind in giving a try on that?

**Comment by tmursch** [comment]
Works, thanks!

**Comment by tmursch** [comment]
Unfortunately the change did not persist after a reboot and reverted back. Do you know the name of the CSS elements that control the header and main input box?

![image](https://user-images.githubusercontent.com/32589462/61397206-36c90480-a87e-11e9-8932-df085135b53c.png)
![image](https://user-images.githubusercontent.com/32589462/61397220-421c3000-a87e-11e9-8eb7-38f3064fa8ff.png)

**Comment by leoandreotti** [comment]
I've made some changes today to the code. Would you mind to replicate the changes from the instructions?

**Comment by tmursch** [comment]
The custom (CSS) theme changes do not persist after quitting and restarting the Slack client. The header and main input go back to white per https://github.com/leoandreotti/slack-dark-theme/issues/14#issuecomment-512454101

**Comment by leoandreotti** [comment]
I have just tested with my windows 10 machine. after deploying the code that is now on the instructions I was able to restart and clear cache, and reset slack and make the CSS changes persist.

**Comment by tmursch** [comment]
Works after complete wipe and reinstall. Good to go.
