### ISSUE TITLE
Not working anymore on Slack 4.0.1

### ISSUE THREAD

**Issue by emanuelarico** [leoandreotti/slack-dark-theme#15]
Hi,
this morning I foudn slack updated to 4.0.1, and the workaround to use the dark skin is not working anymore. Can someone help me? Thank you!

**Comment by leoandreotti** [comment]
Hi @emanuelarico,

have you applied the instructions in your config files again after the update?

**Comment by emanuelarico** [comment]
To made it work I had to do a clean unstall. I don't know why. Now it's working perfectly, thank you, and thank you for your job! 👍
