### ISSUE TITLE
Windows instructions don't work

### ISSUE THREAD

**Issue by slshults** [leoandreotti/slack-dark-theme#16]
Thanks for this!  My eyes appreciate it.

I wasn't able to get it working with the Windows installation instructions in your README. (It could be how the instructions are written, or it could be how I [mis]interpreted them but following those instructions didn't work for me.)  Luckily, I had an idea of how it should work, so...

The instructions below are what what worked for me. If you'd like to update your ReadMe, it may help others reach joy quicker than was able to.  I'm running Windows 10 x64 (1903)

Prerequisites: 
1. Install 7-Zip: https://www.7-zip.org/download.html
2. Install the Asar7z plugin (http://www.tc4shell.com/en/7zip/asar/), and make sure you pick the version that matches your 7-zip install (32bit or 64bit): 

1. Exit Slack

2. Open Windows Explorer and navigate to %homepath%\AppData\Local\slack\app-4.0.1\resources\
(or, after future updates: %homepath%\AppData\Local\slack[versionDirectory]\resources\ )

3. Locate the file named "app.asar", then right-click on it and choose to "Open With..." and select 7-Zip (do not "Extract" it!)  (If this is your first time using 7-Zip from the context menu, you'll need to tell Windows where it is. There are multiple exe.s in the 7-Zip folder. The one you want is named "7zFM.exe")

4. You should now be viewing the contents of app.asar in 7-Zip. In 7-Zip navigate into the '/dist/' folder, then right-click on file named 'ssb-interop.bundle.js', and choose "edit."

5. That'll open the file in Notepad (it will load/open noticeably slowly due to the very long unbroken lines of text in the file.)  Go to the bottom of that file, put your cursor after the last character in the file and hit [enter].  Now copy/paste the the code that you prefer (using external CSS or using local CSS) to the end of the file.  

6. Save the file, then exit Notepad.

6. When asked by 7-Zip whether to update the archive, choose "OK" or "Yes". (If it doesn't ask, go back to step 1 and try again, but read more slowly this time. :-) )

7. Start Slack

8. Enjoy squinting less.

**Comment by leoandreotti** [comment]
Thank you @slshults,  I've updated the readme with your detailed instructions.
