### ISSUE TITLE
Code or text snippet text not showing up.

### ISSUE THREAD

**Issue by raunoodem** [leoandreotti/slack-dark-theme#17]
Hey. 

When creating a code or text snippet - the text is the same color as the background. The only way I can read the text is by selecting the text.

**Comment by leoandreotti** [comment]
Hi @Bulletye and thanks for your message. I will do my best to fix this asap.

**Comment by leoandreotti** [comment]
It's done. You can clear cache and restart!

**Comment by tmursch** [comment]
Hi @leoandreotti – can you share the code change made to correct his? Was it simply this? https://github.com/leoandreotti/slack-dark-theme/commit/f2c9b40f72ad99d8b794ec234f3b17d39b9e6cbd#diff-fa5fdb9fc3c76dcfc23d79b05968a23a

**Comment by raunoodem** [comment]
@leoandreotti Thank you for such a fast fix :)
