### ISSUE TITLE
make the commands matching screen less bright

### ISSUE THREAD

**Issue by dvanlunen** [leoandreotti/slack-dark-theme#2]
if you type `/` it brings up commands and it is very bright:

![screenshot from 2018-11-10 21-29-32](https://user-images.githubusercontent.com/11760121/48308313-ebf92f00-e52f-11e8-81aa-56c15a76e761.png)

**Comment by leoandreotti** [comment]
Hi,

I have placed a fix.

![image](https://user-images.githubusercontent.com/34519982/48629257-4bc45f80-e9a0-11e8-96fa-c0c65415cf8e.png)

Thank you for your contribution
