### ISSUE TITLE
Thread text is not visible in dark background

### ISSUE THREAD

**Issue by kvithayathil** [leoandreotti/slack-dark-theme#4]
Great work on the theme. One thing I've noticed is that the text in threads is dark which makes it hard to read against the dark background. See the attached screenshot:

<img width="371" alt="screenshot 2019-01-24 at 11 00 04" src="https://user-images.githubusercontent.com/1056073/51690783-63831a00-1fc7-11e9-93eb-cadd9920fc08.png">

**Comment by leoandreotti** [comment]
Hi @kvithayathil and thank you for your contribution. I will fix this as soon as possible.

**Comment by leoandreotti** [comment]
Hi @kvithayathil, I have just updated the CSS code with the corrections. Please use Help -> Troubleshooting -> Clear cache and Restart to reload and check if the fix is ok.

Thank you for your contribution.

**Comment by kvithayathil** [comment]
awesome work @leoandreotti 👍
