### ISSUE TITLE
Emoji lookup is off

### ISSUE THREAD

**Issue by ZeroInputCtrl** [leoandreotti/slack-dark-theme#5]
Changing the sub section headers (if possible) would likely tie it together better.

![image](https://user-images.githubusercontent.com/2280933/52064870-75266d80-2543-11e9-9945-acb873cd2ab3.png)

**Comment by leoandreotti** [comment]
Hi @BaneOfSerenity . Thank you for your contribution. I will fix this issue as soon as possible.

**Comment by leoandreotti** [comment]
Hi @BaneOfSerenity, I have just updated the CSS code with the corrections. Please use Help -> Troubleshooting -> Clear cache and Restart to reload and check if the fix is ok.

Thank you for your contribution.

**Comment by ZeroInputCtrl** [comment]
👍 :)
