### ISSUE TITLE
Browse channels not readable

### ISSUE THREAD

**Issue by ZeroInputCtrl** [leoandreotti/slack-dark-theme#6]
Channel text is hard to read unless hovered over.
![image](https://user-images.githubusercontent.com/2280933/52226652-9062e700-287b-11e9-998d-83f546e07932.png)

**Comment by leoandreotti** [comment]
Hi @BaneOfSerenity ,

I have updated CSS and instructions for Slack 4.0 on Mac and Linux. Please try again using the new instructions.
