### ISSUE TITLE
Create a channel black text

### ISSUE THREAD

**Issue by ZeroInputCtrl** [leoandreotti/slack-dark-theme#7]
Public/Private description is black on dark gray
![image](https://user-images.githubusercontent.com/2280933/52226733-c607d000-287b-11e9-97bc-5e0df8600a6a.png)

**Comment by leoandreotti** [comment]
Hi @BaneOfSerenity ,

I have updated CSS and instructions for Slack 4.0 on Mac and Linux. Please try again using the new instructions.
