### ISSUE TITLE
Set a status white background

### ISSUE THREAD

**Issue by ZeroInputCtrl** [leoandreotti/slack-dark-theme#8]
![image](https://user-images.githubusercontent.com/2280933/52226864-18e18780-287c-11e9-9767-fc2d28ce9ea0.png)

**Comment by leoandreotti** [comment]
Hi @BaneOfSerenity, thank you for your contribution. I am a little low in time at this moment but I can see that there are, still, several style fixes and I am counting with your contribution on pointing that. Thank you!!

**Comment by leoandreotti** [comment]
Hi @BaneOfSerenity ,

I have updated CSS and instructions for Slack 4.0 on Mac and Linux. Please try again using the new instructions.
