### ISSUE TITLE
Selected text in code snippet not showing up

### ISSUE THREAD

**Issue by jgerstle** [leoandreotti/slack-dark-theme#9]
Steps:
1. Create code or text snippet
1. Add text to the snippet section
1. Select it

There is no highlight. The text gets selected, but it's impossible to see what's selected

Thanks again for creating this

**Comment by leoandreotti** [comment]
Hi jgerstle, thank you for your contribution. I am a little low in time at this moment but I can see that there are, still, several style fixes and I am counting with your contribution on pointing that. Thank you!!

**Comment by leoandreotti** [comment]
Hi @jgerstle,

I have updated CSS and instructions for Slack 4.0 on Mac and Linux. Please try again using the new instructions.
